baseURL: "https://guilhermec94.github.io/tinysteps.github.io/"
languageCode: en-us
title: Tiny Steps
theme: ["PaperMod"]
pagination:
  pagerSize: 10

# Taxonomias
taxonomies:
  category: categories
  tag: tags

# Parâmetros PaperMod
params:
  env: production
  description: "Taking little steps into software engineering"
  author: "Guilherme Carvalho"
  defaultTheme: dark # light/dark
  showReadingTime: true
  showBreadCrumbs: true
  showPostNavLinks: true
  showCodeCopyButtons: true
  showShareButtons: false
  showPostCategories: true
  disableThemeToggle: false
  comments: false

  mainSections: ["posts"]

  assets:
    favicon: "favicon.ico"
    favicon32x32: "favicon-32x32.png"
    favicon96x96: "favicon-96x96.png"
    apple_touch_icon: "apple-touch-icon.png"

  homeInfoParams:
    Title: ""
    Content: "Taking little steps into software engineering"
    image: "t-logo.png"
  profileMode:
    enabled: true
    title: ""
    subtitle: "Taking little steps into software engineering"
    imageUrl: "t-logo.png"
    imageTitle: "TinySteps Logo"
    buttons:
      - name: "Read the posts"
        url: "posts/"

  socialIcons:
    - name: github
      url: "https://github.com/guilhermec94"

# Menus principais
menu:
  main:
    - name: "Posts"
      url: "posts/"
      weight: 10

# Build
buildDrafts: false
enableRobotsTXT: true
